# .github/workflows/build-and-push.yml (VERSÃO CORRIGIDA E DINÂMICA)

name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo
        run: echo "repository=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push php-fpm image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/common/php-fpm/Dockerfile
          target: production
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.repository }}/php-fpm:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/php-fpm:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/php-fpm:buildcache,mode=max

      - name: Build and push nginx (web) image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/nginx/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.repository }}/web:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/web:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/web:buildcache,mode=max

      - name: Build and push php-cli image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/php-cli/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.repository }}/php-cli:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/php-cli:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/php-cli:buildcache,mode=max

      - name: Build and push API (python) image
        uses: docker/build-push-action@v5
        with:
          # contexto na pasta api (Dockerfile está em api/Dockerfile)
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repository }}/api:latest
            ghcr.io/${{ steps.repo.outputs.repository }}/api:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/api:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.repository }}/api:buildcache,mode=max
