# .github/workflows/laravel-ci.yml

name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura o ambiente PHP com a versão mais recente do Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, pdo, pdo_pgsql, zip, dom # Adicionada a extensão 'dom', que pode ser necessária
          tools: composer:v2

      # 3. Copia o .env para rodar os comandos artisan
      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # 4. Instala as dependências do Composer (com verbosidade máxima)
      # O padrão do 'composer install' é instalar as dependências de dev, a menos que a flag --no-dev seja usada.
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      # 5. Gera a chave da aplicação
      - name: Generate application key
        run: php artisan key:generate

      # 6. Executa as verificações de qualidade e os testes
      - name: Run Analysis & Tests
        run: |
          vendor/bin/pint --test
          vendor/bin/phpstan analyse
          php artisan test